# https://aka.ms/yaml

trigger:
- Dev

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'
  solutionPath: '**/*.sln'
  projectPath: 'AgentAchieve/AgentAchieve.Web/AgentAchieve.Web.csproj' 
  
steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    packageType: 'sdk'
    version: '8.x'
    performMultiLevelLookup: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '$(solutionPath)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(solutionPath)'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)'
    zipAfterPublish: true

- task: DownloadSecureFile@1
  name: publishProfile
  inputs:
    secureFile: 'AgentAchieveDev.PublishSettings' 

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'PublishProfile'
    PublishProfilePath: '$(publishProfile.secureFilePath)' 
    Package: '$(Build.ArtifactStagingDirectory)/**/*.zip'